ecomapp/urls.py
from django.urls import path
from .views import *

app_name ="ecomapp"
urlpatterns = [
    path("",HomeView.as_view(),name='home'),
    path("about/",AboutView.as_view(),name='about'),
    path("contact/",ContactView.as_view(),name='contact'),
    path("all-products/",AllProductView.as_view(),name='allproducts'),
    path("productdetials/<slug:slug>",ProductDetail.as_view(),name='productdetials'),
    path("add-to-cart/<int:pro_id>",AddToCartView.as_view(),name='addtocart'),
    path("mycart/",MyCart.as_view(),name='mycart'),
    path("managecart/<int:cp_id>",ManageCartView.as_view(),name="managecart"),
    path("emptycart/",EmptyCartView.as_view(),name="emptycart"),
    path("checkout/",CheckoutView.as_view(),name="checkout"),
    path("register/",CustomerRegisterView.as_view(),name="register"),
    path("logout/",CustomerLogoutView.as_view(),name="logout"),
    path("login/",CustomerLoginView.as_view(),name="login"),
    path("profile/",CustomerProfileView.as_view(),name="profile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(), name="customerorderdetail"),
    path("search/",SearchView.as_view(),name="search"),
    path("cancelorder/<int:pk>",CustomerCancelOrderView.as_view(),name="cancelorder"),


    # Admin urls functionality
    path("adminlogin/",AdminLoginView.as_view(),name="adminlogin"),
    path("adminhome/",AdminHomeView.as_view(),name="adminhome"),
    path("admin-order-detail/<int:pk>",AdminOrderDetailView.as_view(),name="admindetail"),
    path("admin-all-order/",AdminAllOrderView.as_view(),name="adminallorder"),
    path("admin-status-<int:pk>-change",AdminOrderStatusView.as_view(),name="adminstatus"),

]

ecomapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse_lazy


# Create your models here.

class Admin(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    def __str__(self):
        return self.user.username


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products')
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=300, null=True, blank=True)
    return_policy = models.CharField(max_length=300, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Order: " + str(self.id)

    def get_cancel_order_url(self):
        return reverse_lazy('ecomapp:CustomerCancelOrderView', args=[self.pk])

templates/adminpages/admin_base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title%}Admin Base{% endblock %}</title>
  </head>
  <body>
  <div class="container">
    <a href="{% url 'ecomapp:adminhome'%}">Home</a>|
    <a href="{% url 'ecomapp:home'%}" target="_blank">Visit site</a>|
     <a href="{% url 'ecomapp:adminallorder'%}">All Orders</a>|
  {% block main %}


  {% endblock %}
  </div>
  </body>
</html>

templates/adminpages/admin_home.html
{% extends 'adminpages/admin_base.html'%}
{% block title %}AdminHome{% endblock%}
{% block main%}
<div class="container">
    <h1 class="text-center">Welcome to <span class="text-danger">KINNE HO</span></h1>
 <div class="row">
     <div class="col-md-12">
         <h3>Pending Orders</h3>
         <table class="table">
                <thead>
                <tr>
                    <th>SN</th>
                    <th>Customer</th>
                     <th>Order ID</th>
                    <th>Order on</th>
                    <th>Amount</th>
                </tr>
                </thead>
                 <tbody>
                {% for order in orders %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td><a href="{% url 'ecomapp:admindetail' order.id %}">#ORDER_{{order.id}}</a></td>
                    <td>{{order.ordered_by}}</td>
                      <td>{{order.created_at}}</td>
                      <td>{{order.total}}</td>
                </tr>
                {% endfor %}
         </tbody>
         </table>
     </div>
 </div>
</div>
{% endblock %}

templates/adminpages/admin_login.html
{% extends 'adminpages/admin_base.html'%}
{% load bootstrap %}
{% block title %}Admin Login{% endblock%}
{% block main%}
<div class="container">
        <h3>Admin Log in</h3>
        <form action="" method="POST">
            {% csrf_token %}
            {{form | bootstrap_horizontal}}
            {% if error %}
            <li style="color:red;">{{error}}</li>
            {%endif%}
            <button type="submit" class="btn btn-info">Log in</button>
        </form>
    </div>
{% endblock %}

templates/adminpages/adminorderdetails.html
{% extends 'adminpages/admin_base.html'%}
{% block title %}Order Details{% endblock%}
{% load humanize %}
{% block main%}
<style>
    .help-block{
      color : red;
    }
</style>
    <div class="container">
        <div class="row">
              <div class="col-md-6">
                <h3>Admin Orders Details</h3>
                <p><span class="font-weight-bold">ORDER_ID:</span>{{ord_obj.id}}</p>
                 <p><span class="font-weight-bold">Order Satus:</span>{{ord_obj.order_status}}</p>
                  <p><span class="font-weight-bold">Order On:</span> {{ord_obj.created_at}}({{ord_obj.created_at|timesince}}ago)</p>
                  <p><span class="font-weight-bold">Customer Information:</span>{{ord_obj.ordered_by}}</p>
                  <p><span class="font-weight-bold">Shipping Address:</span>By {{ord_obj.shipping_address}} ({{ord_obj.email}})  </p><br>
                  <h4>Order Items</h4>
            <table class="table">
                <thead>
                <tr>
                    <th>SN</th>
                    <th>Item</th>
                    <th>Rate</th>
                    <th>Quantity</th>
                    <th>Subtotal</th>
                </tr>
                </thead>
                <tbody>
                {% for cp in ord_obj.cart.cartproduct_set.all%}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td><a target="blank" href="/productdetials/{{cp.product.slug}}">{{cp.product.title}} ({{cp.product.id}})</a></td>
                    <td>{{cp.rate}}</td>
                      <td>{{cp.quantity}}</td>
                      <td>{{cp.subtotal}}</td>
                </tr>
                {% endfor %}
                <tr>
                    <th colspan="4" class="text-right">Total:</th>
                    <th>Rs.{{ord_obj.total | intcomma}}</th>
                </tr>
                </tbody>
            </table>

                  <form action="{% url 'ecomapp:adminstatus' ord_obj.id%}" method="POST">
                      {% csrf_token %}
                      <select name="status" >
                           {% for i,j in allstatus %}
                          <option value="{{i}}" {% if i == ord_obj.order_status %}Status{% endif%}>{{j}}</option>
                          {% endfor %}
                      </select>
                      <button type="submit" class="btn btn-info ml-4">Changes</button>
                  </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/adminpages/alladminorders.html
{% extends 'adminpages/admin_base.html'%}
{% block title %}All Orders {% endblock%}
{% block main%}
<div class="container">
 <div class="row">
     <div class="col-md-12">
         <h3>All Orders List</h3>
         <table class="table">
                <thead>
                <tr>
                    <th>SN</th>
                    <th>Customer</th>
                     <th>Order ID</th>
                    <th>Order on</th>
                    <th>Amount</th>
                    <th>Status</th>
                </tr>
                </thead>
                 <tbody>
                {% for order in allorders %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td><a href="{% url 'ecomapp:admindetail' order.id %}">#ORDER_{{order.id}}</a></td>
                    <td>{{order.ordered_by}}</td>
                      <td>{{order.created_at}}</td>
                      <td>{{order.total}}</td>
                      <td>{{order.order_status}}</td>
                </tr>
                {% endfor %}
         </tbody>
         </table>
     </div>
 </div>
</div>
{% endblock %}