ecomapp/urls.py
from django.urls import path
from .views import *

app_name ="ecomapp"
urlpatterns = [
    path("",HomeView.as_view(),name='home'),
    path("about/",AboutView.as_view(),name='about'),
    path("contact/",ContactView.as_view(),name='contact'),
    path("all-products/",AllProductView.as_view(),name='allproducts'),
    path("productdetials/<slug:slug>",ProductDetail.as_view(),name='productdetials'),
    path("add-to-cart/<int:pro_id>",AddToCartView.as_view(),name='addtocart'),
    path("mycart/",MyCart.as_view(),name='mycart'),
    path("managecart/<int:cp_id>",ManageCartView.as_view(),name="managecart"),
    path("emptycart/",EmptyCartView.as_view(),name="emptycart"),
    path("checkout/",CheckoutView.as_view(),name="checkout"),
    path("register/",CustomerRegisterView.as_view(),name="register"),
    path("logout/",CustomerLogoutView.as_view(),name="logout"),
    path("login/",CustomerLoginView.as_view(),name="login"),
    path("profile/",CustomerProfileView.as_view(),name="profile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(), name="customerorderdetail"),
    path("search/",SearchView.as_view(),name="search"),
    path("cancelorder/<int:pk>",CustomerCancelOrderView.as_view(),name="cancelorder"),


    # Admin urls functionality
    path("adminlogin/",AdminLoginView.as_view(),name="adminlogin"),
    path("adminhome/",AdminHomeView.as_view(),name="adminhome"),
    path("admin-order-detail/<int:pk>",AdminOrderDetailView.as_view(),name="admindetail"),
    path("admin-all-order/",AdminAllOrderView.as_view(),name="adminallorder"),
    path("admin-status-<int:pk>-change",AdminOrderStatusView.as_view(),name="adminstatus"),

]

ecomapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse_lazy


# Create your models here.

class Admin(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    def __str__(self):
        return self.user.username


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products')
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=300, null=True, blank=True)
    return_policy = models.CharField(max_length=300, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Order: " + str(self.id)

    def get_cancel_order_url(self):
        return reverse_lazy('ecomapp:CustomerCancelOrderView', args=[self.pk])

templates/about.html
{% extends 'base.html'%}
{% block title %}About Us{% endblock%}
{% block main%}
<style>
    body {
    /* Typography Declarations */
    color: #222222;
    font-size: 1em;
    font-family: "Open Sans", "Helvetica Neue", sans-serif;
}

.content-footer,
.masthead-heading,
.masthead-intro {
  text-align: center;
}

.masthead {
  padding: 6em 0;
  background-image: url('https://i.imgur.com/yGmrlyg.jpg');
  background-size: cover;
  background-repeat: no-repeat;
  border-top: solid 1em #FFCF33;
}

.masthead-intro {
    /* Layout Declarations */
    margin-bottom: 0.1em;
    /* Typography Declarations */
    font-family: "Gentium Book Basic", Georgia, serif;
    font-size: 2em;
}

.masthead-heading {
    /* Layout Declarations */
    color: #F1C863;
    margin-top: -0.2em;
    /* Typography Declarations */
    font-family: "Open Sans", "Helvetica Neue", sans-serif;
    font-weight: bold;
    font-size: 6em;
    letter-spacing: -0.02em;
    text-transform: uppercase;
}

.introduction-section,
.location-section,
.questions-section {
    max-width: 38em;
    margin-left: auto;
    margin-right: auto;
    margin-top: 2em;
}

.introduction-section > p,
.location-section > p,
.questions-section,
.content-footer > p {
    /* Typography Declarations */
    font-weight: 300;
    letter-spacing: 0.05em;
}

.questions-section > h2 {
    font-family: "Gentium Book Basic", Georgia, serif;
    font-size: 1.2em;
    font-weight: bold;
    /* Layout */
    margin: 2em 0 1em 0;
}

section > h1 {
    margin-top: 2em;
}

.content-footer,
.masthead-heading,
.masthead-intro {
  text-align: center;
}

.masthead {
  padding: 6em 0;
  background-image: url('https://i.imgur.com/yGmrlyg.jpg');
  background-size: cover;
  background-repeat: no-repeat;
  border-top: solid 1em #FFCF33;
}

.masthead-intro {
  margin-bottom: 0.1em;
  font-family: "Gentium Book Basic", Georgia, serif;
    font-size: 2em;
}

.masthead-heading {
  margin-top: -0.2em;
  font-family: "Open Sans", "Helvetica Neue", sans-serif;
  font-weight: bold;
  font-size: 6em;
  letter-spacing: -0.02em;
  text-transform: uppercase;
}
.introduction > p,
.location > p,
.content-footer > p {
    /* Typography Declarations */
    font-weight: 300;
    letter-spacing: 0.05em;
}
h2 {
    /* Typography Declarations */
    font-family: "Gentium Book Basic", Georgia, serif;
    font-size: 1.2em;
    font-weight: bold;
}

.introduction-section,
.location-section,
.questions-section {
    max-width: 38em;
    margin-left: auto;
    margin-right: auto;
    margin-top: 2em;
}
.content-footer {
  margin: 50px 0;
  padding: 20px 0;
  text-align: center;
  background-color: #73A8C2;
  text-decoration: none;
}
.social > li {
  display: inline-block;
  margin: 0 5px;
}
.content-footer > p {
  color: #F7EDE1;
}
a {
    font-weight: bold;
    text-decoration: none;
    color: #F1C863;
}

@media only screen and (max-width: 500px) {
    .masthead {
        padding: 3em 0;
    }
    .masthead-heading {
        font-size: 3em;
    }
    .content-footer {
        padding: 2em 2.5em;
  }
}
</style>
<header class='masthead'>
  <p class='masthead-intro'>Hi I'm</p>
  <h1 class='masthead-heading'>Nikov!</h1>
</header>
<section class="introduction-section">
    <h1>Introduction</h1>
    <p>I am a construction business owner, part time marketer, and soon to be web developer.</p>
    <p>I love the internet, technology, and building beautiful things.</p>
</section>
<section class="location-section">
    <h1>Where I'm From</h1>
    <p>I'm originally from Toronto, Ontario. </p>
</section>
<section class="questions-section">
    <h1>More About Me</h1>
    <h2>What are your favorite hobbies?</h2>
    <p>My favorite hobby is building things on the internet like ecommerce sites and email marketing campaigns.</p>
    <h2>What's your dream job?</h2>
    <p>My dream job is similar to my current job except I would like to be building software instead of buildings.</p>
    <h2>Where do you live?</h2>
    <p>I live on a rural acreage, but I'm close to Ottawa and Montreal.</p>
    <h2>Why do you want to be a web developer?</h2>
    <p>Because programming is awesome and programming for the internet is even more awesome.</p>
</section>

<footer class="content-footer">
    <p>Say hi to me on these social networks:</p>
    <ul class="social">
        <li><a class="css-is-deranged" href="_INSERT_GITHUB_URL_HERE_">GitHub</a></li>
        <li><a class="css-is-deranged" href="_INSERT_TWITTER_URL_HERE_">Twitter</a></li>
        <li><a class="css-is-deranged" href="_INSERT_GOOGLE+_URL_HERE_">Google+</a></li>
    </ul>

</footer>
{% endblock %}

templates/addtocart.html
{% extends 'base.html'%}
{% block title %}Add To Carts{% endblock%}
{% block main%}
<div class="container">
            <h2>Product add sucessfully in Cart.</h2>
</div>
{% endblock %}

templates/allproducts.html
{% extends 'base.html'%}
{% block title %}All Products{% endblock%}
{% block main%}
<div class="container">
    <h1>All Products</h1>
    <hr>
    {% for cat in allcategories %}
    <h4>{{cat.title}}</h4><hr>
    <div class="row">
        <div class="row mt-3">
{% for p in cat.product_set.all %}
 <div class="col-md-3">
  <div class="m-4">
      <h3><a href="/productdetials/{{p.slug}}">{{p.title}}</a></h3>
<img src="{{p.image.url}}" alt="" class="img-fluid" style="height:2500; object-fit:cover;"><br><br>
  <p>Price: <strike>{{p.marked_price}}</strike> Rs.{{p.selling_price}}</p>
  <a href="{% url 'ecomapp:addtocart' p.id%}" class="btn btn-primary">Add To Cart</a>
   </div>
</div>
 {% endfor %}
</div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title%}{% endblock %}</title>
  </head>
  <body>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#"><span class="text-danger" style="font-weight:bold;">KINNE</span>HO</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="/all-products">Category</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'ecomapp:mycart'%}">My Cart</a>
      </li>
         {% if request.user.customer %}
       <li class="nav-item">
           <a href="#" class="nav-link"> Welcome {{request.user.username}}</a>
         </li>
       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         My Account</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'ecomapp:logout'%}">Log out</a>
          <a class="dropdown-item" href="{% url 'ecomapp:profile'%}">My Profile</a>
        </div>
      </li>

      {% else %}
        <li class="nav-item">
        <a class="nav-link" href="/about">About us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contact">Contact us</a>
      </li>
       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Join us </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{%url 'ecomapp:login'%}">Log in</a>
          <a class="dropdown-item" href="{%url 'ecomapp:register'%}">Register</a>
        </div>
      </li>
        {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'ecomapp:search' %}" method="GET">
      <input class="form-control mr-sm-2" type="search" name="keyword" placeholder="Search" aria-label="Search" required>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    <hr>
  {% block main %}
    <h1>Hello, world!</h1>
  {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/cancelOrder.html
{% extends 'base.html'%}
{% load bootstrap %}
{% block title %}Cancel Order{% endblock%}
{% block main%}
<div class="container">
        <h3>Cancel Order</h3>
        <form action="" method="POST">
            {% csrf_token %}
            <p>Are you sure you want to cancel ?</p>
            <button type="submit" class="btn btn-danger">Cancel Order</button>
        </form>
    </div>
{% endblock %}

templates/checkout.html
{% extends 'base.html'%}
{% block title %}Checkout{% endblock%}
{% load bootstrap %}
{% block main%}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Items in the cart</h3>
            <a class="btn btn-success mb-4" href="{% url 'ecomapp:mycart' %}">Update Cart</a>
 <table class="table">
                <thead>
                <tr>
                    <th>SN</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Subtotal</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{cp.product.title}}</td>
                    <td>{{cp.quantity}}</td>
                    <td>{{cp.rate}}</td>
                    <td>{{cp.subtotal}}</td>
                    </tr>
                {% endfor %}
                <tr>
                    <th colspan="4" class="text-right">Total</th>
                    <th>Rs. {{cart.total}}</th>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <h3>Checkout Form</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form | bootstrap_horizontal}}
                <button type="submit" class="btn btn-info">Place Order</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/customerorderdetail.html
{% extends 'base.html'%}
{% block title %}Registration{% endblock%}
{% load humanize %}
{% block main%}
<style>
    .help-block{
      color : red;
    }
</style>
    <div class="container">
        <div class="row">
              <div class="col-md-6">
                <h3>Customer Order Details</h3>
                <p><span class="font-weight-bold">ORDER_ID:</span>{{ord_obj.id}}</p>
                 <p><span class="font-weight-bold">Order Satus:</span>{{ord_obj.order_status}}</p>
                  <p><span class="font-weight-bold">Order On:</span> {{ord_obj.created_at}}({{ord_obj.created_at|timesince}}ago)</p>
                  <p><span class="font-weight-bold">Customer Information:</span>{{ord_obj.ordered_by}}</p>
                  <p><span class="font-weight-bold">Shipping Address:</span>By {{ord_obj.shipping_address}} ({{ord_obj.email}})  </p><br>
                  <h4>Order Items</h4>
                   <table class="table">
                <thead>
                <tr>
                    <th>SN</th>
                    <th>Item</th>
                    <th>Rate</th>
                    <th>Quantity</th>
                    <th>Subtotal</th>
                </tr>
                </thead>

                <tbody>
                {% for cp in ord_obj.cart.cartproduct_set.all%}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td><a target="blank" href="/productdetials/{{cp.product.slug}}">{{cp.product.title}} ({{cp.product.id}})</a></td>
                    <td>{{cp.rate}}</td>
                      <td>{{cp.quantity}}</td>
                      <td>{{cp.subtotal}}</td>
                </tr>
                {% endfor %}
                <tr>
                    <th colspan="4" class="text-right">Total:</th>
                    <th>Rs.{{ord_obj.total | intcomma}}</th>
                </tr>
                </tbody>
            </div>
        </div>
    </div>
{% endblock %}

templates/home.html
{% extends 'base.html'%}
{% block title %}Home{% endblock%}
{% block main%}
<div class="container">
    <h1 class="text-center">Welcome to <span class="text-danger" style="font-weight:bold;">KINNE HO</span></h1>
 <hr>
<div class="row mt-3">
{% for p in product_list %}
 <div class="col-md-3">
  <div class="m-4">
      <h3><a href="/productdetials/{{p.slug}}">{{p.title}}</a></h3>
<img src="{{p.image.url}}" alt="" class="img-fluid" style="height:2500; object-fit:cover;"><br><br>
  <p>Price: <strike>{{p.marked_price}}</strike> Rs.{{p.selling_price}}</p>
  <a href="{% url 'ecomapp:addtocart' p.id %}" class="btn btn-primary">Add To Cart</a>
   </div>
</div>
 {% endfor %}
</div>
    <nav aria-label="...">
  <ul class="pagination">
      {% if product_list.has_previous %}
    <li class="page-item  ">
      <a class="page-link" href="?page={{ product_list.previous_page_number }}" >Previous</a>
    </li>
      {% else %}
      <li class="page-item disable ">
      <a class="page-link" href="#" tabindex="-1" >Previous</a>
    </li>
      {% endif %}
      {% for i in product_list.paginator.page_range%}
      {% if i == product_list.number %}
        <li class="page-item active"><a class="page-link">{{i}}</a></li>
      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
      {% endif %}
      {% endfor %}
      {% if product_list.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ product_list.next_page_number }}">Next</a>
    </li>
      {% else %}
        <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1" >Next</a>
    </li>
      {% endif%}
  </ul>
</nav>
</div>
{% endblock %}

templates/login.html
{% extends 'base.html'%}
{% load bootstrap %}
{% block title %}Log in{% endblock%}
{% block main%}
<div class="container">
        <h3>User Log in</h3>
        <form action="" method="POST">
            {% csrf_token %}
            {{form | bootstrap_horizontal}}
            {% if error %}
            <li style="color:red;">{{error}}</li>
            {%endif%}
            <button type="submit" class="btn btn-info">Log in</button>
            <p>or don't have account?<a href="{% url 'ecomapp:register'%}{%if request.GET.next%}?next={{request.GET.next}}{%endif%}"> Register here</a></p>
        </form>
    </div>
{% endblock %}

templates/mycart.html
{% extends 'base.html'%}
{% block title %}My Cart{% endblock%}
{% block main%}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h4>Items in my cart</h4>
            <table class="table">
                <thead>
                <tr>
                    <th>SN</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Subtotal</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{cp.product.title}}</td>
                    <td>{{cp.quantity}}</td>
                    <td>{{cp.rate}}</td>
                    <td>{{cp.subtotal}}</td>
                    <td>
                        <a href="{% url 'ecomapp:managecart' cp.id%}?action=inc" class="btn btn-primary">+</a>
                        <a href="{% url 'ecomapp:managecart' cp.id%}?action=dcr" class="btn btn-warning">-</a>
                        <a href="{% url 'ecomapp:managecart' cp.id%}?action=rmv" class="btn btn-danger">X</a>
                    </td>
                    </tr>
                    {% endfor %}
                <tr>
                    <th colspan="4" class="text-right">Total</th>
                    <th>{{cart.total}}</th>
                    {% if cart.cartproduct_set.all %}
                    <th><a href="{% url 'ecomapp:emptycart'%}" class="btn btn-danger">Empty Cart</a></th>
                    {% endif %}
                </tr>
                <tr>
                    {% if cart.cartproduct_set.all %}
                    <th><a  class="btn btn-info" href="{% url 'ecomapp:checkout'%}">Checkout</a></th>
                    {% endif %}
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/productdetails.html
{% extends 'base.html'%}
{% block title %}Product Description{% endblock%}
{% block main%}
<div class="container">
    <h3>Product: {{product.title}}</h3>
    <hr>
    <div class="row">
        <div class="col-md-6">
    <img src="{{product.image.url}}" alt="" class="img-fluid">
        </div>
        <div class="col-md-6">
            <h4>{{product.title}}</h4>
            <h5>Category: {{product.category}} (Viewed: {{product.view_count}} times)</h5>
             <h5>Price: <strike>{{product.marked_price}}</strike> Rs.{{product.selling_price}}</h5>
            <a href="{% url 'ecomapp:addtocart' product.id%}" class="btn btn-primary">Add To Cart</a><hr>
            <p class="text-info">Warranty: {{product.warranty}}</p>
            <p class="text-info">Return Policy: {{product.return_policy}}</p><hr>
            <p>{{product.description}}</p>


        </div>
    </div>

</div>
{% endblock %}

templates/register.html
{% extends 'base.html'%}
{% load bootstrap %}
{% block title %}Registration{% endblock%}
{% block main%}
<style>
    .help-block{
      color : red;
    }
</style>
    <div class="container">
        <h3>User Registration</h3>
        <form action="" method="POST">
            {% csrf_token %}
            {{form | bootstrap_horizontal}}
            <button type="submit" class="btn btn-info">Sign Up</button>
            <p>Already have account?<a href="{% url 'ecomapp:login'%}"> Login here</a></p>
        </form>
    </div>
{% endblock %}

templates/search.html
{% extends 'base.html'%}
{% block title %}Search{% endblock%}
{% block main%}
<style>
    .help-block{
      color : red;
    }
</style>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h3>Search Result for <span class="text-success">"{{request.GET.keyword}}"</span></h3>
                 <hr>
                {% if results%}
                {% for result in results %}
                <div class="row">
                    <div class="col-md-6">
                        <img src="{{ result.image.url}}" class="img-fluid" alt="">
                    </div>
                    <div class="col-md-6">
                        <h4><a href="{% url 'ecomapp:productdetials' result.slug %}">{{result.title}}</a></h4>
                        <p>{{result.description}}</p>
                        <a href="{% url 'ecomapp:addtocart' result.id %}" class="btn btn-primary">Add To Cart</a>
                    </div>
                </div>

                {%  endfor %}
                {%else%}
                <h2>No Result Found</h2>
                {% endif %}

            </div>
        </div>
    </div>
{% endblock %}